// AUTO-GENERATED by scripts/generate-works-manifest.mjs
// Do NOT edit manually. Run `npm run generate:works` to refresh,
// or just run `npm run dev` / `npm run build` — it runs automatically.

export type GeneratedWork = {
  src: string;
  title: string;
  category: string;
  /** "portrait" | "wide" | "square" */
  ar: string;
};

export const generatedWorks: GeneratedWork[] = [
  {
    "src": "/works/26aad82942c33842836ba4489e2dcc6e.png",
    "title": "26AAD829",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/2bdb8b5e421c4ed1c7f65d1f07b49fae.jpg",
    "title": "2BDB8B5E",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/37e7bf1fb0fb5336c5db3683fd89b4f6.jpg",
    "title": "37E7BF1F",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/3b156a9e1beeefb33c75742e624061d7.jpg",
    "title": "3B156A9E",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/503ba5585c1539c0851af8687e2e05df.png",
    "title": "503BA558",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/561d02963c35cbb94f3a5e6542e87506.png",
    "title": "561D0296",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/64f17f6723655330d83b1657cd51519a.jpg",
    "title": "64F17F67",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/75dd8186ae8116f9ab37b5059639de2f.png",
    "title": "75DD8186",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/8850bd4610d74878faf0b55813ea5c17.jpg",
    "title": "8850BD46",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/a5c22696ecb1b92eb1483f9c23b19e6b.png",
    "title": "A5C22696",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/a875b181aaca15d875c17026a64df004.jpg",
    "title": "A875B181",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/aadecfcdfced01532b564aafcadc90ff.jpg",
    "title": "AADECFCD",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/df31b3df8a6b227ace01d9989877c4c9.jpg",
    "title": "DF31B3DF",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/e0797f2b7a9c9cc201e4c62bca7b50db.jpg",
    "title": "E0797F2B",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/e6da65c470b315d7c6747fba70cfc280.jpg",
    "title": "E6DA65C4",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/fbbbf54656e663e8353ea97695af5f05.jpg",
    "title": "FBBBF546",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/fdb9cfee890bbd0da28e900dfab6a8ea.png",
    "title": "FDB9CFEE",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/floral-portrait-study.webp",
    "title": "Floral Portrait Study",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/modern-portrait-study.webp",
    "title": "Modern Portrait Study",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/radiant-awakening.webp",
    "title": "Radiant Awakening",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/red-car-editorial.webp",
    "title": "Red Car Editorial",
    "category": "Visual Direction Study",
    "ar": "wide"
  },
  {
    "src": "/works/the-new-rules.webp",
    "title": "The New Rules",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/time-culture-maker.webp",
    "title": "Time Culture Maker",
    "category": "Visual Direction Study",
    "ar": "portrait"
  },
  {
    "src": "/works/volt-no-more-filters.webp",
    "title": "Volt No More Filters",
    "category": "Visual Direction Study",
    "ar": "portrait"
  }
];
